### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by sandekuk** [SvenWalter/webpack-war-archiver-plugin#2]
I get the below error when I integrate this plugin to my Angular2-rc4 + Webpack application.

_Unhandled rejection Error: EPERM: operation not permitted, stat 'C:\Config.Msi'
    at Error (native)
    at Object.fs.statSync (fs.js:981:18)
    at EasyZip.zipFolder (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\easy-zip\easyzip.js:83:14)
    at Compiler.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack-war-archiver-plugin\index.js:15:13)
    at Compiler.applyPlugins (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\tapable\lib\Tapable.js:26:37)
    at Watching._done (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:78:17)
    at Watching.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:61:18)
    at Compiler.emitRecords (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:282:37)
    at Watching.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:58:19)
    at C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:275:11
    at Compiler.next (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\tapable\lib\Tapable.js:67:11)
    at Compiler.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\copy-webpack-plugin\dist\index.js:190:13)
    at Compiler.applyPluginsAsync (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.afterEmit (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:272:8)
    at Compiler.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:267:14)
    at C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:209:22)
    at Compiler.emitFiles (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:235:20)
    at MemoryFileSystem.(anonymous function) [as mkdirp](C:Usersug561eprojectsWebUisrcmainwebappnode_moduleswebpack-dev-middlewarenode_modulesmemory-fslibMemoryFileSystem.js:283:10)
    at Compiler.<anonymous> (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\webpack\lib\Compiler.js:229:25)
    at Compiler.next (C:\Users\ug561e\projects\WebUi\src\main\webapp\node_modules\tapable\lib\Tapable.js:67:11)
[default] Checking started in a separate process..._

**Comment by sishirbasanta** [comment]
Hi @sandekuk , did you fix the problem ? I have the same problem but mine says 'D:\System Volume Information' instead.

**Comment by SvenWalter** [comment]
Not yet but I can have a closer look over the weekend to fix it.
